# Generated by Django 5.0.4 on 2024-04-16 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('production_order', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('IDs', models.IntegerField()),
                ('design', models.TextField()),
                ('employee', models.CharField(max_length=100)),
                ('tool', models.CharField(max_length=100)),
                ('work_step', models.CharField(max_length=100)),
                ('workplace', models.CharField(max_length=100)),
                ('current_date', models.DateField()),
                ('total_time', models.DurationField(default=datetime.timedelta(seconds=1))),
            ],
            options={
                'db_table': 'form_data',
            },
        ),
    ]
